name: Release from src-frontend/package.json

on:
    push:
        branches: [main]
        paths:
            - 'src-frontend/package.json'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Read version from src-frontend/package.json
              id: pkg
              run: |
                  VERSION=$(node -p "require('./src-frontend/package.json').version")
                  echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                  echo "tag=v$VERSION"    >> "$GITHUB_OUTPUT"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.pkg.outputs.tag }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
